title: DASH LAB
author: Simon Woo
email: swoo@g.skku.edu
url: "https://s00ne.github.io"
baseurl: ""
description:  # this means to ignore newlines until "baseurl:"
  Data-driven + AI + Security + HCI Lab

twitter_username: none
github_username:  DASH-lab

sass:
    style: compressed
