title: DASH LAB
author: Simon Woo
email: swoo@g.skku.edu
description: > # this means to ignore newlines until "baseurl:"
  Data-driven + AI + Security + HCI Lab

twitter_username: -
github_username:  DASH-lab

sass:
    style: compressed
