title: DASH LAB
author: Simon Woo
email: swoo@g.skku.edu
baseurl: https://s00ne.github.io/
description:  # this means to ignore newlines until "baseurl:"
  Data-driven + AI + Security + HCI Lab

twitter_username: none
github_username:  DASH-lab

sass:
    style: compressed
